feat (SFML3D.txt): draw in 3D

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -32,6 +32,14 @@ jobs:
           mkdir build && cd build
           cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
           cmake --build .
+          if [ -f "arcade" ]; then
+            echo "Executable found"
+            exit 0
+          else
+            ls -alF
+            echo "Executable not found"
+            exit 1
+          fi
 
   mirroring:
     runs-on: ubuntu-latest
